AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CICDApiGatewayPreTestFunction:
    Properties:
      CodeUri: s3://cicdsample.appcohesion.io/01e4df4c952b32c73f999b0c6f1b2c7b
      Environment:
        Variables:
          S3_BUCKET: cicdsample.appcohesion.io
      FunctionName: CiCdApiGatewayPreTestManager
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
